# Spring Boot 配置示例
# 文件上传路径配置

logging:
  level:
    com.com.baomidou.mybatisplus: debug
    org.apache.ibatis: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    global-config:
      db-config:
        id-type: auto
    pagination:
      enable: true
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8090
spring:
  web:
    resources:
      static-locations: file:D:/code/bs/swzl2/swzl/upload/images/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swzl-bs?userUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true
  # 配置静态资源的访问路径
